{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "30742e85_302f3fd0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1000671
      },
      "writtenOn": "2025-04-21T21:17:02Z",
      "side": 1,
      "message": "updating gson to 2.13.0 causes this error, not sure why:\n\n.cache/bazel/60705e27b74c370310311cbb011c59a0/external/rules_jvm_external~~maven~maven/BUILD:53:11: in deps attribute of jvm_import rule @@rules_jvm_external~~maven~maven//:com_google_errorprone_error_prone_annotations: rule \u0027@@rules_jvm_external~~maven~maven//:com_google_errorprone_error_prone_type_annotations\u0027 does not exist",
      "revId": "269b086acbb9c0a12c842a849f43dfb99a6a1ba1",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8462d5eb_29adbc6a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1020855
      },
      "writtenOn": "2025-04-21T23:54:48Z",
      "side": 1,
      "message": "Fixed lib/jmh/BUILD dependencies and then .benchmarks seem to use a junit class (?!). \n\nAfter this, I did a bazel clean, bazel fetch and bazel build //..., and it built fine. Could you try?",
      "parentUuid": "30742e85_302f3fd0",
      "revId": "269b086acbb9c0a12c842a849f43dfb99a6a1ba1",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "23622f5b_c5d36cb2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1020855
      },
      "writtenOn": "2025-04-22T16:42:09Z",
      "side": 1,
      "message": "Ah, I got that error with gson 2.13 . Fixed updating MODULE.bazel with\n\n+        \"com.google.code.gson:gson:2.13.0\",\n+        \"com.google.errorprone:error_prone_type_annotations:2.38.0\",\n\n(Having trouble now uploading the change)",
      "parentUuid": "8462d5eb_29adbc6a",
      "revId": "269b086acbb9c0a12c842a849f43dfb99a6a1ba1",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0950d3e1_ddb3b9a3",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1000671
      },
      "writtenOn": "2025-04-22T22:52:26Z",
      "side": 1,
      "message": "I have a new patchset for this change and the other changes in this series. Though pushing it for review fails with the error\n\n```\r\nremote: commit 34f090f: Reviewing commit: 34f090f6\nremote: commit 34f090f: Authored by: Ivan Frade \u003cifrade@google.com\u003e\nremote: commit 34f090f:\nremote: commit 34f090f: Reviewing commit: 34f090f65e1b6d89c869a37b5d68bfbc802a990e\nremote: commit 34f090f: Authored by: Ivan Frade \u003cifrade@google.com\u003e\nremote: commit 34f090f: Could not find an Eclipse user with mail \u0027ifrade@google.com\u0027 for author of commit 34f090f65e1b6d89c869a37b5d68bfbc802a990e\nremote: commit 34f090f:\nremote: commit 34f090f: Please see http://wiki.eclipse.org/ECA\n```\n\nLooks like this is caused by the issues with the Eclipse accounts API reported here\nhttps://www.eclipsestatus.io/",
      "parentUuid": "23622f5b_c5d36cb2",
      "revId": "269b086acbb9c0a12c842a849f43dfb99a6a1ba1",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}